### ISSUE TITLE
Thank You: Left side Padding is not equal to the landscape view

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#111]
Device:
Ipad (portrait)

![image](https://cloud.githubusercontent.com/assets/13363508/9954052/5ca603ba-5e18-11e5-8069-62585fbd6626.png)

**Comment by suniltitan** [comment]
The padding will decrease according to the size of the device.

**Comment by maehtitan** [comment]
<h5> That's why I need it to be fixed and make it consistent with the landscape view
