### ISSUE TITLE
Footer section: Gap between text and titan logo should be 14px as per psd. Currently is used 2px.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#16]
![footer-title01](https://cloud.githubusercontent.com/assets/13309730/9576355/9a774406-4ff4-11e5-8dd5-7d541c360a4f.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed
![design2](https://cloud.githubusercontent.com/assets/13309730/9808750/af1f8d4c-580e-11e5-9cc6-5259a3264ead.png)

**Comment by suniltitan** [comment]
Please check the screenshot it has been fixed before.
![footer](https://cloud.githubusercontent.com/assets/14212899/9845642/1ebb140e-5aea-11e5-826f-be370993777d.jpg)
