### ISSUE TITLE
Banner section: Banner section is distorting when new banner is added.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#19]
![banner01](https://cloud.githubusercontent.com/assets/13309730/9576939/52112208-4ffa-11e5-9440-6e1c93138044.jpg)

**Comment by mahender-sowedane** [comment]
Please explain why it's invalid?

**Comment by suniltitan** [comment]
Because that is not a bug , I have added a new banner and did not find this issue.

**Comment by mahender-sowedane** [comment]
While doing testing i found that issue, still not fixed.
after adding new banner, kindly observe when banner is rotating you can easily identify..
and kindly stop working on this project it is currently in QA not assigned to you
thanks!
