### ISSUE TITLE
Our Suppliers(Home page): Gap should be 67px. Currently is used 65px.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#20]
![oursupplygp](https://cloud.githubusercontent.com/assets/13309730/9577244/9ad6e192-4ffc-11e5-9a04-9405b8cf9fff.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed
![design_1](https://cloud.githubusercontent.com/assets/13309730/9808677/e0a8ec06-580d-11e5-9bb5-43af85c4aa89.png)

**Comment by suniltitan** [comment]
It has been fixed before, Please check the screenshot.
![our-suppliers](https://cloud.githubusercontent.com/assets/14212899/9845554/6e4a9ae0-5ae9-11e5-9255-79efbb7c200b.jpg)
