### ISSUE TITLE
Gallery page: Gallery custom post is not implemented as per scope. Currently is used NextGen gallery.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#22]
![gallery_custom01](https://cloud.githubusercontent.com/assets/13309730/9577362/bf67f0fe-4ffd-11e5-9791-2c8f61ebe4c8.png)

**Comment by suniltitan** [comment]
Scope has been updated.

**Comment by mahender-sowedane** [comment]
Remove unused posts in admin panel

![gallery002](https://cloud.githubusercontent.com/assets/13309730/9842669/bf356874-5ace-11e5-95fa-e5bcb6a3c30a.jpg)
