### ISSUE TITLE
Services page: Ordered lists are not styled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#24]
1. Applicable for all pages.

![services_orderlist](https://cloud.githubusercontent.com/assets/13309730/9577522/2f32daba-4fff-11e5-8b57-bd9ff80c6cbc.png)

**Comment by mahender-sowedane** [comment]
Please explain why it is invalid?

**Comment by suniltitan** [comment]
I have updated the post with ordered lists and it working fine.

**Comment by mahender-sowedane** [comment]
Have a look on above screenshot and i found that issue while doing testing.
kindly fix it.?
