### ISSUE TITLE
Our Services(Home page): There is no option to control lead-ins order

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#34]
![lead-insordr](https://cloud.githubusercontent.com/assets/13309730/9578416/6f7ba3c4-5007-11e5-9457-6fc18ff73919.jpg)

**Comment by suniltitan** [comment]
Have option for reorder on the left hand side options. Lead-ins > Re-order

**Comment by mahender-sowedane** [comment]
As per standard it should have an Order Attribute
