### ISSUE TITLE
Gallery page: Album's are not styled

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#37]
![gallery-albums_many](https://cloud.githubusercontent.com/assets/13309730/9579021/b98e912e-500c-11e5-800a-8912d60bbe37.png)

**Comment by mahender-sowedane** [comment]
Please explain why it's invalid?

**Comment by suniltitan** [comment]
That bug has already been fixed, Can you send me the URL for this page ?

**Comment by mahender-sowedane** [comment]
Then why your changed that label status as 'Invalid' once you fixed.?

**Comment by mahender-sowedane** [comment]
Then why your changed that label status as 'Invalid' once you fixed.?

**Comment by suniltitan** [comment]
While inserting the gallery you will have to select the template.
