### ISSUE TITLE
Gallery page: Featured image is not displaying in gallery page.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Western-Kitchens#39]
1. Applicable to all pages

![gallery_fetru](https://cloud.githubusercontent.com/assets/13309730/9579077/44122bee-500d-11e5-85dd-f0ceb3afd914.png)

**Comment by mahender-sowedane** [comment]
Please explain why it's invalid, if it's invalid then why your added that featured image what is the use of that option..?

**Comment by suniltitan** [comment]
Please check the scope document it has been updated. Now the gallery page is using Nggallery.
