### ISSUE TITLE
Admin - User Email: General Settings and User Email doesn't match

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#57]
<b>General Settings</b>.
![image](https://cloud.githubusercontent.com/assets/13363508/9926217/373a1490-5d46-11e5-9c25-9131598bc32d.png)
<b>User Email</b>.
![image](https://cloud.githubusercontent.com/assets/13363508/9926230/475f8d3c-5d46-11e5-9ce9-1ae0f40093e1.png)

**Comment by suniltitan** [comment]
Updated the general settings.
