### ISSUE TITLE
Custom Field - Contact Us Form: Shortcode was point to the dummy page which shortcode ACF doesn't appears in the actual page at first and it only shows after clicking the update button

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#65]
![image](https://cloud.githubusercontent.com/assets/13363508/9927521/c38c91a6-5d51-11e5-9f85-b2383f31bc98.png)

<b>Are you using the Contact Us Form shortcodes in the contact us page or just did the hard code in showing the form coz currently it is not pointing to contact us page instead in Testing Page02? </b>

**Comment by suniltitan** [comment]
I have removed the contactus form - custom field (It was dummy not used by any page/posts)

**Comment by maehtitan** [comment]
As per TL, Contact us form in the contact us page should use the Shortcode, coz we are not encourage to implement it as hard-code.

**Comment by maehtitan** [comment]
Contact Us page still not using the Shortcode
![image](https://cloud.githubusercontent.com/assets/13363508/10092819/445329ae-637d-11e5-8b4d-bb281f2a5041.png)

**Comment by maehtitan** [comment]
Shortcode ACF still not found in contact us page

**Comment by suniltitan** [comment]
Do you want shortcode to be in WYSIWYG Text Editor, Please advise.

**Comment by maehtitan** [comment]
Please check it here: http://electricalcontractor-2015.stage.titanweb.com.au/wp-admin/post.php?post=62&action=edit

**Comment by suniltitan** [comment]
ACF Form Shortcode is added to Contact form page.
