### ISSUE TITLE
Services: Images are linked to another post, should be on the specific post only

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#70]
<b>Example below:
I was clicking the "Test Services - Text Only" thumbnail images but I was landed to the next post thumbnails</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9928623/0241dc50-5d5a-11e5-8ffd-dde858f2fa71.png)

**Comment by suniltitan** [comment]
I have tested and it works fine.

**Comment by maehtitan** [comment]
There was a prev and next button previously and images are linked to each other but it was all gone now that's why I cannot replicate the issue I reported above
