### ISSUE TITLE
Gallery - Extended Album: Please design the images just like how the Basic album styled and also remove the hover state behaviour because it doesn't exist from the design

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#74]
![image](https://cloud.githubusercontent.com/assets/13363508/9929484/7cc12c2e-5d5f-11e5-8b9a-4b0ebf42fdc6.png)

**Comment by suniltitan** [comment]
This bug has been fixed you need to select the template while inserting the gallery.

**Comment by maehtitan** [comment]
It has to be documented in the User Guide on how to insert the template.

**Comment by suniltitan** [comment]
Fixed, If you select the display type it will select the template for examples : If you select display type as  "NextGEN Basic Compact Album" the template "Parent Theme :album-compact.php" will be selected.
