### ISSUE TITLE
News: As per Standard, Use ShortenText() if linked to a single page and Number of lines limit will depend on the design

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Western-Kitchens#77]
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/post-title-and-post-desription

**Comment by maehtitan** [comment]
shorten text number of lines limit should be consistent and will depend on the design if not mention in the scope

**Comment by suniltitan** [comment]
I have limited the number of characters as per the design which is 545 characters.

**Comment by maehtitan** [comment]
Sorry still not achieved compared to the design
![image](https://cloud.githubusercontent.com/assets/13363508/10094202/5dca2a56-638f-11e5-9fe0-fbde3df1a5dd.png)

And also I have check the character counts here: 
![image](https://cloud.githubusercontent.com/assets/13363508/10094241/ecfa523c-638f-11e5-8219-07a935795567.png)

Found out that it is 1011 counds on the first post
